//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS201724112128
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Department = new HashSet<Department>();
            this.Equipment = new HashSet<Equipment>();
        }
    
        public int EmployeeId { get; set; }
        public string EmployeePassword { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeePhone { get; set; }
        public Nullable<bool> IfManager { get; set; }
        public Nullable<int> EmployeeBelongDep { get; set; }
    
        public virtual ICollection<Department> Department { get; set; }
        public virtual Department Department1 { get; set; }
        public virtual ICollection<Equipment> Equipment { get; set; }
    }
}
